### ISSUE TITLE
Application won't start

### ISSUE THREAD

**Issue by andreicek** [irosenb/whatsthewifi#9]
Hi,

I tried starting the app with an open WiFi network, and with a "protected" network. On both the app won't start.

My OSX version is 10.10.4 (14E17e), MacBook Air (13-inch, Mid 2013).

**Comment by irosenb** [comment]
Oh hm…Sorry I didn't see this earlier 🙉

**Comment by irosenb** [comment]
@andreicek you signed into the protected one right?

**Comment by andreicek** [comment]
Yes!
